# Generated by Django 3.0.5 on 2020-04-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_book_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
