# Generated by Django 3.0.5 on 2020-05-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200419_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
